# Disable the spring security default configuration from spring-boot-actuator
management.security.enabled: true
security.basic.enabled: false

# Disable Jolokia - An http/json bridge for remote JMX access
endpoints.jolokia.enabled: false

# security configuration (this key should be unique for your application, and kept secret)
jhipster.security.rememberme.key: 7d7f3a93f13c894e8dcc8297be55e298a036e073

async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

mail:
    host: localhost
    port: 25
    username:
    password:
    protocol: smtp
    tls: false
    auth: false
    from: jjztsacaapp1@localhost


swagger:
    title: jjztsacaapp1 API
    description: jjztsacaapp1 applications and beyond!
    version: 0.0.1
    termsOfServiceUrl: http://jhipster.github.io/
    contact: JJ Zabkar
    license: Apache 2.0
    licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html

spring:
  application:
    name: jjztsacaapp1
    
onebusaway:
    arrivalsAndDeparturesService:
         uri: http://api.pugetsound.onebusaway.org/api/where/arrivals-and-departures-for-stop/{stopId}.json?key={apiKey}
    routeService:
         uri: http://api.pugetsound.onebusaway.org/api/where/route/{routeId}.json?key={apiKey}
    stopService:
         uri: http://api.pugetsound.onebusaway.org/api/where/stop/{stopId}.json?key={apiKey}
